name: Build Docs

on: 
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Using node ${{ node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ node_version }}
    - name: npm install and build
      run: |
        npm install
        npm start
    - name: checkout gh-pages
      run: | 
        git checkout gh-pages
        git pull origin gh-pages
    - name: update files 
      run: |
        cp -R build/assets .
        cp build/index.html .
    - name: push pages to Github
      run: |
        git add .
        git commit -m Updating docs
        git push origin
